### ISSUE TITLE
Better description of boot option

### ISSUE THREAD

**Issue by ThomasUllrich666** [ibm-cloud-docs/satellite#48]
URL: https://cloud.ibm.com/docs/satellite?topic=satellite-attach-hosts#attach-rhcos-hosts

Bullet point nr2 is totally unclear: 
`Boot your RHCOS host and include the file path to the ignition script as the --user-data. For example: --user-data @/tmp/attach_hypershift.ign.`

Can you please describe the command in detail (and not just one parameter?)

**Comment by kersten1** [comment]
Well, this is a hard one because it depends on what sort of host you are using. For the bare metal servers that we attached, we put the ignition script into COS and then added a path to COS on the installation screen for that server. For AWS, I normally use the GUI and add it to advanced tab. So I am not sure what we can add here because we don't know what type of on-prem host you are using. 

Can you help me understand what your specific use case is and then we can look at adding it as an example?

**Comment by kersten1** [comment]
@ThomasUllrich666 can you help me understand what you might need for this?

**Comment by ThomasUllrich666** [comment]
sure...
consider yourself as someone who reads the documentation above the first time.

1. you should download a host scritpt. Fine thats easy.. But in facts it is the ignition file
2. you should boot the RHCOS host. Easy as well. An then you write that the user should include the --user-data parameter to the ignition script and add the ignition file that was downloaded? didn't make much sense because you didn't download a file you download the ignition file that is part of the parameter.... 

I think it will be clear if you try it on you own.. If anything is unclear just give me a call on slack.

**Comment by kersten1** [comment]
Updated the topic to include more examples of what to do. We are also looking for other ways to improve this section. In the meantime, I am closing this issue. In the future, rather than opening an issue in a public repo so that we are required to have a public discussion, can you please contact us via slack and tag docs. If you are unsure of the process of doing this, please contact me directly.
