### ISSUE TITLE
Change the Satellite Link Responsibility Model

### ISSUE THREAD

**Issue by lionelmace** [ibm-cloud-docs/satellite#49]
Today, the model stays **N/A** for IBM Responsibility.
In reality, IBM is responsible of keeping the Satellite Link UP and applying changes to Satellite Link and recovering if there is a 7 days disconnections.

https://cloud.ibm.com/docs/satellite?topic=satellite-responsibilities

![image](https://github.com/ibm-cloud-docs/satellite/assets/12241613/7b5bebc4-853d-4cbb-968f-26528da7c797)

![image](https://github.com/ibm-cloud-docs/satellite/assets/12241613/8140e7ee-d6d9-4f2a-9e34-b26d7fbb90df)

@davetropeano

**Comment by dan-waugh** [comment]
Hi @lionelmace , thanks for the comment. This disaster recover item for link is really around the underlying connectivity....the tunnel will come up if the route is there, but that connectivity is the client's responsibility.

The other aspects, like recovery after a 7 day disconnect, is shared with the location/host/config items.  

Does this make sense to you?

**Comment by gcoon151** [comment]
"IBM is responsible of keeping the Satellite Link UP" The service running in the cloud has to be up but when you just vaguely say Satellite Link half of the link tunnel runs outside of our control which is why it's a shared responsibility. Let's be careful saying this as you did. 

"and applying changes to Satellite Link" -- The cloud side for security and service purposes yes. 

"and recovering if there is a 7 days disconnections." -- This is still not Disaster Recovery. DR has much more detailed terms which are not related to a transit service like link. Our service is deployed across MZRs in Iaas which by definition are triple redundant DR. If a full MZR goes down, the whole of IBM services goes down. If a customer requires more than that they can use more than one MZR also and apply additional load balancing across that though it would start to get prohibitively expensive and complicated for any reasonable use case.

**Comment by kersten1** [comment]
Took discussion to internal source.
