### ISSUE TITLE
Wrong info in IP adresses in Satellite Connector overview docs

### ISSUE THREAD

**Issue by MariamMassoud93** [ibm-cloud-docs/satellite#55]
Link: https://cloud.ibm.com/docs/satellite?topic=satellite-understand-connectors

A client has been through this and said that the information in IP adress is wrong. Please check? 
Frankfurt
* 		Destination IP addresses: 149.81.188.130, 158.177.75.210, 161.156.38.2
* 		Destination hostnames: c-01-ws.eu-de.link.satellite.cloud.ibm.com, api.link.satellite.cloud.ibm.com
* 		Protocol and ports: HTTPS 443

**Comment by neelashah** [comment]
@MariamMassoud93 Can you elaborate on what you mean by the IP address being wrong? 

- If I dig c-01-ws.eu-de.link.satellite.cloud.ibm.com I will get the 3 IPs that are listed. 
- I notice we have not listed the IPs for api.link.satellite.cloud.ibm.com - is this what you mean that the IP list is incomplete because its missing the two IPs for api.link.satellite.cloud.ibm.com which are 184.28.29.55 and 184.28.29.49

**Comment by derekpoindexter** [comment]
moving to slack
