### ISSUE TITLE
SELinux is required on OpenShift nodes

### ISSUE THREAD

**Issue by teruz** [ibm-cloud-docs/satellite#9]
Currently SELinux is required on OpenShift worker nodes due to this issue:
https://github.ibm.com/alchemy-containers/satellite-planning/issues/1080

It should be explicitly written in host requirements on cloud docs.

**Comment by artberger** [comment]
@teruz Thanks for raising this issue. So our automation checks to make sure that SELinux is enabled when adding the host to the Satellite location. By chance did you run into the issue because SELinux was disabled some time after attaching the host? I am updating our docs to say that after setting up the host, you shouldn't delete any of the host packages or alter the default settings.

**Comment by kersten1** [comment]
Updated on this page - https://cloud.ibm.com/docs/satellite?topic=satellite-host-reqs#reqs-host-packages - Thank you!
